#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"
rm -rf AZRO_SITE_TEST_READY_ROOT
mkdir AZRO_SITE_TEST_READY_ROOT
ditto "AZRO_FAST_PART_1_CORE_DOCS_COPY_CONTENTS_TO_PUBLISH_ROOT" AZRO_SITE_TEST_READY_ROOT
ditto "AZRO_FAST_PART_2_MEDIA_COPY_CONTENTS_TO_PUBLISH_ROOT" AZRO_SITE_TEST_READY_ROOT
echo "Done. Publish the CONTENTS of AZRO_SITE_TEST_READY_ROOT to https://zsend.github.io/AzroTest/"
